### ISSUE TITLE
Source of truth for start time

### ISSUE THREAD

**Issue by janmayer** [R3BRootGroup/R3BRoot#332]
For NeuLAND calibration and online analysis, we currently rely on other detectors. The problem is that these detectors change from experiment to experiment and within the experiment the offset can change (e.g. on DAQ reboot). 

For example, in the [current version of the NeuLAND Online Analysis Script]( https://github.com/R3BRootGroup/R3BRoot/pull/331/files#diff-7c26177db7ad9142911d9e5a59ef9228) we do this with an ifdef switch, taking LOS by default and  Sofia if it exists - not ideal. In addition, there is always some logic involved to extract the start time from the other detectors' data – something that does not belong in the NeuLAND code but in its own class
The offset is a parameter given in the online analysis script, 
```C++
    auto nlhit = new R3BNeulandCal2Hit();
    nlhit->SetDistanceToTarget(distanceToTarget);
    nlhit->SetGlobalTimeOffset(7300);
    run->AddTask(nlhit);
```
Which obviously makes analyzing runs with different offsets together impossible.

Is there a common class, a “source of truth”, that I can simply query/consume for the start time? That should also take care of the changing part of the time offset as a run parameter (ParFile).
Depending on the experiment, one would add the respective task for the right start detector (which fill the same Container with the start time) to the macro.
How do the other detectors handle the start time?

**Comment by inkdot7** [comment]
In land02 this is handled by having an experiment-independent incoming tracking.  The available detectors are declared, together with positions (z) and their capabilities (x, y, dE, t).  Then the data is used to its fullest extent to calculate the position and time on target (using fits), as well as charge (through energy loss).  These sets of parameters are then available as x0, y0, t0 to other detectors.  One caveat is that the reconstruction of the incoming detectors needs to happen before other detectors that need this information runs.

Just a start detector is not enough, as it is not giving time-on-target - it needs extrapolation along z.  What land02 did not do very well was adapting to movement of detectors, since this info was in a C source file...

**Comment by kresan** [comment]
Is the issue still relevant?

**Comment by janmayer** [comment]
Providing the start time is something that affects the online and offline analysis of experimental data, which I only have limited insight into. As a NeuLAND developer, I just want to consume the start time.

I did "solve" it for some of the previous experiments in https://github.com/R3BRootGroup/R3BRoot/issues/332 but I’m interfering with the code of the other detector groups there.

I'm a bit worried that no one else has talked about this. What I think could be happening is that everyone, again, writes his own analysis and additions to R3BRoot without committing them back*, solving problems that are already solved or should be solved globally. In their code, they might, again, do stuff in overly complex god-tasks that instead should belong in separate classes with the respective detectors.

*) Really, where are all the commits?

**Comment by jose-luis-rs** [comment]
I think that this is also solved with the current R3BLosProvideTStart class
