### ISSUE TITLE
Preview: Lightweight FairTasks PoC

### ISSUE THREAD

**Issue by klenze** [R3BRootGroup/R3BRoot#436]
Writing a typical FairTask traditionally means creating lots of boilerplate code:
* Adding an TClonesArray* member field for every R3BFooData one wants to use
* Add a constructor which uses member initialization lists to set these to nullptr (I see few default member initializers)
* Adding an Init() method in which the TCAs are assigned from FairRootManager::Instance()->GetObject("FooName"), typically using a C-style cast, plus some error handling
* Adding an Exec() method where the (assumed) TCAs are queried for their wlements, and these elements are C-style cast to whatever the programmer assumes them to be
* Adding a Destructor which deletes all the TCA pointers on the probably erroneous assumption that FairRootManager::GetObject transfers ownership (but then again no harm was ever done by a [double free](https://cwe.mitre.org/data/definitions/415.html) or [use after free](https://cwe.mitre.org/data/definitions/416.html))

For Parameters, the situation is quite similar, but seems to involve two more methods, SetParContainers() and SetParameter().

Eternal optimist that I am, I think the reason why our FairTasks get so long is that given these Boilerplate requirements, it is much easier to add the stuff into an existing Task than writing a new one. 

Using some template magic (and some features of C++17), one can make this procedure both much safer (e.g. using dynamic_casts) and hide the complexity from the individual FairTasks. 
[Here](https://gist.github.com/klenze/77b9ff56606268301bfb0b9226d0c1e2) is a sample FairTask meant to write out WRTS of s494 events where the ToFD saw a carbon-ish ion. (The cxx is just two lines, the include and the ClassImp macro.)

The boilerplate per R3BFooData practically goes down to ``#include "R3BFooData.h``. To use it, one can then simply use 
``for(auto& h: roothacks::Container<R3BFooData>::get())``

(If the TCA-name is not unique per type (unlikely, given that we have four otherwise identical ``R3BWRFooData``), one would have to specify the TCA object name as well. Of course, the mapping ClassName->ObjectName must be maintained somewhere, one line per FooData.)

I will probably make a PR with the supporting code (plus a short sample task) when my analysis is done.

**Comment by janmayer** [comment]
That is short indeed. 

I think many problems are due to old code that get copied over and over again - easy to spot with all the superfluous comments in the header file.

Most boilerplate indeed stems from the TClonesArrays, especially if you want to to it right.
I have developed templated classes in [TCAConnector](https://github.com/R3BRootGroup/R3BRoot/blob/dev/neuland/shared/TCAConnector.h):

- TCAInputConnector
- TCAOptionalInputConnector
- TCAOutputConnector

Which make it extremely easy to see what is going in and out. They handle:

- all the boilerplate, including
    - throwing an error if branch is not present, except when its optional
    - explicitly set (and check!) the data type it should contain
- take the branch name at construction (allows for easy setting in task constructor)
- deliver either `std::vector<T*>`  or `<std::vector<T>`.  (*)

Now, all of that **should have been done by FairRoot** since the beginning - we really should not have to worry about all these Nullpointer checks, endless casting and type safety, and should leverage all the stuff provided by the stl.


## Example: 
In the header file, see [R3BNeulandDigitizer](https://github.com/R3BRootGroup/R3BRoot/blob/dev/neuland/digitizing/R3BNeulandDigitizer.h)
```C++
    TCAInputConnector<R3BNeulandPoint> fPoints;
    TCAOutputConnector<R3BNeulandHit> fHits;
```

Implementation file [R3BNeulandDigitizer](https://github.com/R3BRootGroup/R3BRoot/blob/dev/neuland/digitizing/R3BNeulandDigitizer.cxx)
In the constructor:
```C++
R3BNeulandDigitizer::R3BNeulandDigitizer(TString input, TString output)
    : FairTask("R3BNeulandDigitizer")
    , fPoints(input)
    , fHits(output)
    // ...
{
}
```

In Init:
```C++
    fPoints.Init();
    fHits.Init();
```

And finally, in Exec:
```C++
fHits.Reset();
for (const auto& point : fPoints.Retrieve()) {
    // ...
}
for (/*...*/)
{
    // ...
    fHits.Insert(std::move(hit));
}
````


*) This conversion to vectors is not 100% optimized, but I believe in return value optimization and improvements in the other code due to not having to deal with TCAs.
