### ISSUE TITLE
Problems with some initializations

### ISSUE THREAD

**Issue by jose-luis-rs** [R3BRootGroup/R3BRoot#555]
Please, **don't use** this kind of initialization:

Int_t nsum_top[fNofPlanes] = { 0 };

**error**: variable-sized object ‘nsum_top’ may not be initialized
         Int_t nsum_top[fNofPlanes] = { 0 };

Thanks in advance

**Comment by klenze** [comment]
A few more comments:
* Variable length arrays (VLAs) are not officially part of C++, but a gcc extension. gcc will tell you that with -pedantic. 
* Initializing an array with more than one element with {0} does what one might assume it does, but for non-obvious reasons: The zeroth element will be initialized by the explicitly given list element 0, while all others will be default-initialized to zero. By contrast, int a[N]={1}; will initialize the zeroth element to one and all the others to zero. IMHO, it is preferable to just default-initialize with int a[N]={} or int a[N]{};
* The C++ standard template library offers vastly better option than C arrays. If your use case requires variable length, std::vector seems like an obvious fit. 
* Finally, contrary to common belief, the correct spelling of the integer type in C/C++ is in fact 'int'. 'Int_t' is just ROOT trying embrace, extend, extinguish (fat chance) C++. While the two are (hopefully) synonymous it's use is somewhat political. (Other (unordered) political pairs like this: "Taiwan" vs "Republic of China", "Free Software" vs "Open Source", "Soviet occupied zone" vs "German Democratic Republic", "war" vs "special military operation"):
* * 'int' signals: "I am a C/C++ programmer (who may happen to occasionally use, amongst other libraries, CERN's ROOT)."
* * 'Int_t' signals: "I identify as a ROOT programmer. I generally prefer to do things the ROOT way, either because I consider ROOT to be superior to standard C++ or because I am unaware of standard C++ solutions."

BTW, @jose-luis-rs, I would recommend running git blame and highlighting the contributor using the at-syntax, otherwise they are likely to miss this.
