### ISSUE TITLE
Issues with Reader when adding timestamps to PSPs

### ISSUE THREAD

**Issue by ajedele** [R3BRootGroup/R3BRoot#636]
I'm currently adding the internal timestamps from the FEBEX to the PSPReader, Mapped2Precal, Precal2Cal and Cal2Hit.

Hans and Bastii added the timing channels to the upexps unpacker and we have successfully generated a new ext_h101_pspx.h file. I tried adding this to the R3BPspxReader header and code by adding the X at the end of EXT_STR_h101_PSP. When I try to do a make in my build directory, I get the following error:

input_line_12:364759:36: error: typedef redefinition with different types ('struct EXT_STR_h101_PSPX_t' vs 'struct EXT_STR_h101_PSP_t')
typedef struct EXT_STR_h101_PSPX_t EXT_STR_h101_PSPX;

input_line_12:271388:3: note: previous definition is here 
} EXT_STR_h101_PSPX;

I think it's getting confused by the 2 different readers and different ext files. This is the final step in adding the timing.

**Comment by jose-luis-rs** [comment]
Hi Andrea
Both data structures seem to have the same data members, so you have to select the last data structure to compile and execute the reader.

**Comment by ajedele** [comment]
Hi Jose Luis,

Ok. How do I select the data structure and execute the reader?

**Comment by jose-luis-rs** [comment]
Could you send me your reader and the new data structure to take a look into and give you the right answer?
Thanks

**Comment by ajedele** [comment]
The path is /u/ajedele/R3BRoot_oldest/r3bsource/

The file is:
R3BPspxReader.cxx
R3BPspxReader.h
ext/ext_h101_pspx.h

I can zip the files otherwise.

**Comment by jose-luis-rs** [comment]
Hello Andrea

I have taken a look into the code and it seems to go in the good direction, but there are some issues:

1) You are using a very old version of R3BRoot, since you want to do a new implementation to share with other collaborators you should start this work from the latest version of R3BRoot. Otherwise your work will not be useful.

2) Your R3BRoot is not under GitHub, this is a problem for you because you cannot track your modifications. The protocol was explained by @morze00 during our collaboration meeting (https://indico.gsi.de/event/14660/contributions/63442/attachments/40000/54600/Panin_AnaWG.pdf). Please, follow the instructions to progress with the work and be able to share your modifications with the others.

3) Your implementation looks fine, but the definition of some variables is missing, for instance the definition of "trigger".

Please, try to do the implementation in the latest version of R3BRoot:
https://github.com/R3BRootGroup/R3BRoot/tree/dev

Thanks in advance

**Comment by ajedele** [comment]
Hi Jose Luis,

I am purposely working on old code. The timing issue I am trying to resolve
is for the s473 experiment and this the code they are using. The timing
implementation is not possible for s515 (wasn't implemented into the DAQ).
We can discuss implementing the code for future experiments, but I would
like to solidify the DAQ for future experiments 1st.

I will add this to GitHub eventually. I am going a little rogue here. If it
works, I will implement it.

Andrea

Am Do., 30. Juni 2022 um 11:59 Uhr schrieb Jose Luis Rodriguez <
***@***.***>:
