### ISSUE TITLE
Event header, ownership and kicking C-style casting out of R3BRoot

### ISSUE THREAD

**Issue by YanzhaoW** [R3BRootGroup/R3BRoot#674]
Hello

## Cause:
I stumbled upon a segmentation fault recently during an online analysis using `FairRunOnline`. For most of the time, the segmentation fault could be caused by an unallocated memory being read due to an overflowing index or getting deleted (e.g. a pointer gets deleted twice). The reason why this happened at this time is because the R3B event header was not set in `FairRunOnline` before its initialisation. (Setting the event header at the beginning is certainly not obvious and even less obvious is the idea that the segmentation fault could be caused by this. )

## Explanation:
If the event header is not set manually by the user, `FairRunOnline` would set it automatically to the type `FairEventHeader` during its initialisation:
```cpp
    if (nullptr == fEvtHeader) {
        fEvtHeader = new FairEventHeader();
    }
```
Later it gets registered by `FairRootManager` with:
```cpp
    fRootManager->Register("EventHeader.", "Event", fEvtHeader, (nullptr != fRootManager->GetSink()));
```
In the end, the event header gets deleted in the deconstructor of `FairRun`. Therefore, any other class using the event header, which is obtained through
```cpp
    fHeader = frm->GetObject("EventHeader.");
```
does not own this object and should not delete it. But it gets deleted in the deconstructor of `R3BUnpackReader`:
https://github.com/R3BRootGroup/R3BRoot/blob/628973f43039266af0f833063a943507efeebc61/r3bsource/base/R3BUnpackReader.cxx#L39-L42
In C++, if one pointer gets deleted multiple times, an undefined behaviour would be caused, which could be program crashing, segmentation fault or nothing.

The deletion of not-owned object is just one of the causes. Another cause is the usage of vicious C-style casting, which is omnipresent in R3BRoot. Let me explain it with the following code from `R3BUcesbSource.cxx`:
https://github.com/R3BRootGroup/R3BRoot/blob/4e2decfab13d80ee412c6dfeabfcc19c4efd4976/r3bsource/base/R3BUcesbSource.cxx#L118-L129
The problem here is manifold: the method `GetObject()` only returns a pointer whose type is `TObject`. But what is the type of the object this pointer points to? Is it certain that the object has the type `R3BEventHeader`? Since [someone](https://github.com/FairRootGroup/FairRoot/issues/1225#issue-1377838222) already complained about type-unsafety in FairRoot, here I only discuss what bad consequences C-style casting can lead to. (Using C-style casting in a type-unsafe program is like adding oil to the fire.)

As I have mentioned previously, if we don't set the event header manually, it would be created in the type of `FairEventHeader` with the name "EventHeader." (again, mystical dot). So here what we get from `GetObject("EventHeader.")` is a pointer pointing to an object of the type `FairEventHeader`. Now we cast it to the type `R3BEventHeader`. The class `R3BEventHeader` is derived from `FairEventHeader`, which requires more memory during its instantiation. It's obvious that this down-casting is illegal and should be forbidden. However, C-style casting gives it a go. In the end, not only does the same memory get deleted multiple times, but some unallocated memories also get deleted. If those unallocated memories are used by another variable, a segmentation fault would be called.

## Suggestions:
1. Don't delete an object that is not owned. Encapsulate the pointer to the owned object inside `std::unique_pointer<>` (with this, deletion is unnecessary).
Ownership is another nightmare in FairRoot. Some objects obtained through `FairRootManager::GetObject()` are owned by `FairRun` ("EventHeader." is one of them) and some are not. One has to go through its source file to find it out!

2. ChBnge all C-style castings to either `static_cast` or `dynamic_cast`. Don't use any castings if implicit casting can be performed. Use `static_cast` if it can be assured by the programmer that the casting is safe and legal. Otherwise, use `dynamic_cast`. (Ref: C++ Core Guidelines ES.48 & Es.49)
The FairRoot community has done this very well. You rarely find any C-style castings over there. 

3. If R3BEventHeader is not set by the user, a fatal message should be called. For example:
    ```cpp
        R3BLOG(INFO, "Register of R3BEventHeader");
        fEventHeader = dynamic_cast<R3BEventHeader*>(frm->GetObject("EventHeader."));
        if (fEventHeader)
        {
            R3BLOG(INFO, "EventHeader. was defined properly");
        }
        else
        {
            R3BLOG(FATAL, "R3BEventHeader was not found!");
        }
    ```
    Or a better way is to check whether it's been set in the `Init()` method. If not, set it here and `FairRunOnline` will register it later. (I link my pull request below.)
#673

**Comment by klenze** [comment]
Welcome to R3BRoot :-)

``<sarcasm>``
In R3BRoot, we don't subscribe to the ownership model of memory management. Just like the LEMO cables in Cave C, after some time, nobody knows anymore what belonged to which group, and when it is time to clean up, everyone just does their best. Thus, in the destructors, we [traditionally free any pointers we find lying around](
https://github.com/R3BRootGroup/R3BRoot/blob/dev/califa/online/R3BCalifaOnlineSpectra.cxx#L109). After all, it is essential that we clean up at the end of the run, otherwise, how would the system reclaim the memory?
We generally do not follow guidelines written by people who are not even physicists and prefer to emulate [ROOT](https://github.com/root-project/root/blob/master/hist/histpainter/src/THistPainter.cxx#L4022) in [all things](https://github.com/root-project/root/blob/master/hist/hist/src/TH3.cxx#L91). 
``</sarcasm>``

With regard to memory management, I think we have to separate two cases.
* Within the event loop, memory leaks are bad and must be fixed. 
* Outside the event loop we realistically do not really care. If the FairTasks get destroyed, the run is over. While we could clean up everything (and would only have to think about what is owned by gDirectory, what is owned by FairRootManager and in which order the FairTasks and Readers are destroyed anyhow), realistically, we can assume that nobody will keep creating and deleting FairTasks in the same process. Realistically, every call to ROOT's Form() is a memory leak. 
* Undefined behavior, on the other hand, is to be avoided. That includes double (or triple) free()s, as well as out of bounds reads/writes. (Stay tuned for another issue w.r.t. that soon). 

Realistically, I would assume that most of the contributors do not even know about dynamic_cast. They just [copy-pasted](https://en.wikipedia.org/wiki/Cargo_cult_programming) some syntax which would make their TClonesArray's spit out whatever type they assumed was in them. 

C++ is not an easy language to learn on the job in any case. Realistically, many contributors have to learn C++ by using code samples from ROOT and R3BRoot to actually solve problems. For them, R3BRoot is the baseline for normal. The integer type just happens to be called Int_t. How should they learn about templates, STL, range based for loops, memory checkers, debuggers, software design principles, core guidelines and so on? We have no code reviews where a reviewer could say "your code might run, but it is actually a bad design, please change it in this or that way". PRs either get merged or get left open if nobody with permissions feels like merging them. Issues (like yours) likewise.

While I do not see eye to eye with regard to everything with the FairRoot (or present-day ROOT) devs, at least some of them acknowledge some of the problems. With R3BRoot, I feel like a nerd complaining about his weird aesthetic preferences when I mention any of them (like C-style casts, or the parameter storage formats, why your constructor perhaps should not have eight arguments, why having code replication is bad, how interpreted root macros are terrible and any issue people have when running them are Just Rewards for them violating the Cosmic Order, how virtually every big open source project makes the branch where development happens their default branch, or how travis should reject code which creates new warnings, etc).

**Comment by jose-luis-rs** [comment]
@YanzhaoW Thanks for the job! If you find more problems like this in the code, please, do the corresponding PR to solve them as soon as possible.
