### ISSUE TITLE
Replacing (non string) C-Arrays

### ISSUE THREAD

**Issue by klenze** [R3BRootGroup/R3BRoot#762]
As I discussed in the meeting a week ago, C arrays are the main source of undefined behavior in our codebase. Some of our devs might always use C arrays correctly, some (like me) will access them within the bounds most of the time, and some will struggle even more. 

Unless we either
* accept that segfaults and undefined behavior are normal
* find a way to turn all our contributors into flawless programmers
C arrays need to go. 

While clang-tidy provided a way to replace upcasts in C style with dynamic_casts (see #759), it can not replace C arrays automatically. 

clang-tidy with cppcoreguidelines-avoid-c-arrays finds some 6272 uses of C-arrays in our codebase. This is a bit to replace by hand, so I propose to fix most of them automatically. 
I propose to replace one dimensional arrays following clang-tidy's suggestions:
* fixed length arrays become ``std::array``
* variable length arrays become ``std::vector``
Furthermore, multi-dimensional arrays become boost::multi_arrays.

There are two pathes forward here:
* Implement the fix in clang-tidy.
  * Pros: we have access to the actual abstract syntax tree
  * Cons: that check is written in C++, might take some time. 
* Write a python script which takes a piece of output of clang-tidy and decides on the replacement ad hoc. 
   * Cons: variable declarations in C/C++ are a nightmare to parse reliably. A sane language would enforce a scheme like "typename variablenames;".  Instead K&R gave us ```int a, *b[10], (*c)(int, int), (*d[5])(int), f(int), x[2][2]={{1,2},{3}}, *z[]={nullptr, nullptr};``` which is a bit more difficult and in the general case probably impossible without the context of which names refer to types or variables. 
    * Pros: it is simple, most of our declarations are not that complicated. If we can reliably detect that some declaration is complicated, that is enough. We can fix a few complex declarations manually. 

At the moment I would prefer to use the python way. But before I start on that, I would have to have the buy-in of the other devs. So if anyone wants to keep using C arrays (except for interfacing with code which needs them,, e.g. ROOT), here and now would be the place to argue for them.

**Comment by klenze** [comment]
@hapol Hector, can you please comment on whether we should replace C arrays or not?

**Comment by hapol** [comment]
Hi,
just my opinion... This action corresponds to a security improvement which is technically relevant but it is also quite delicate performed in this scale, and even more using scripting instead of careful study of each case. Such modification should be performed while ensuring that the changes do not compromise the results of the different task, which is a very difficult duty. So, I would ask proceed carefully and taking all possible measurements to avoid undesirable secondary effects. While it's true that this is one of the main sources of segfaults, I consider more dangerous to make modifications which mislead and confound users with unexpected results or, even worse, wrong and undetected errors. Yes, I know, this could also be an effect of outofbounds C arrays...
So, yes, I consider the replacement useful but I would ask to the developer to be cautious and test as much as possible the results, if possible asking all users to review analysis with the new version.
