### ISSUE TITLE
Problems with GLAD geometry

### ISSUE THREAD

**Issue by jose-luis-rs** [R3BRootGroup/R3BRoot#770]
Hi

In the middle of GLAD we have a piece of metal that generates a shadow in the detectors located behind of GLAD, see attached figure, should I solve this problem?

>
![Screenshot from 2023-01-30 13-09-14](https://user-images.githubusercontent.com/18137822/215473858-898784ca-9777-4be0-af15-6ded7f1886e3.png)

**Comment by jose-luis-rs** [comment]
Hello

I have solved the problems with GLAD (https://github.com/R3BRootGroup/macros/pull/70) and with the PR #774 the new root geometry will be generated automatically during the compilation --> glad_v2023.1.geo.root

These are some pictures for the new version:
![glad1](https://user-images.githubusercontent.com/18137822/216336713-5ead0c05-cb61-478c-9aa6-a098498c4baf.png)
![glad2](https://user-images.githubusercontent.com/18137822/216336751-b5da1686-fd6d-4252-8db5-f265bbbf1d14.png)
![glad3](https://user-images.githubusercontent.com/18137822/216336766-452e1aca-77ee-48f1-a731-dbe5b57d539c.png)
![glad4](https://user-images.githubusercontent.com/18137822/216336779-f298cf32-f79b-4f26-813d-658fca202dd8.png)

**Comment by morze00** [comment]
It looks good! Thank you Jose Luis for fixing this geometry bug. It must have been there quite a long time, probably because such thin line was hard to see. With the new version of FairSoft we should also be able to use correct GLAD geometry definition  from the .gdml file obtained from Daniel's CAD drawing.
