### ISSUE TITLE
Unknown CMake command "fair_pad"

### ISSUE THREAD

**Issue by jose-luis-rs** [R3BRootGroup/R3BRoot#899]
**Describe the bug**
Unknown CMake command "fair_pad" after PR #895

**To Reproduce**
See  https://github.com/R3BRootGroup/sofia/actions/runs/6679213073/job/18151119643?pr=310

**Comment by YanzhaoW** [comment]
Hi, sorry, I didn't see this post.

The reason is because:
```shell
-- Could not find FairCMakeModules. It is recommended to install https://github.com/FairRootGroup/FairCMakeModules
```
in the CI process.

`fair_pad` is included in `FairCMakeModules/modules/FairFormattedOutput.cmake`. So if the FairCmakeModules can't be found, `fair_pad` is not defined, which is also indicated by following lines:

https://github.com/R3BRootGroup/R3BRoot/blob/d67a4f360f89b444f7e4957f4cb1e90ac23f466c/CMakeLists.txt#L78-L85

~~The way to solve this problem is to search FairCMakeModules in config mode:~~
```cmake
find_package(FairCMakeModules 1.0.0 CONFIG)
```

I will make a PR about this.

EDIT:
find_package will fall to CONFIG mode automatically is the searching in module mode fails. Maybe the failure could be caused by `cmake_prefix_path` is defined after the searching.

**Comment by jose-luis-rs** [comment]
Thanks, now it works
